# Header
menu:
  主页: /
  所有文章: /archives
  乱七八糟: /tags/乱七八糟

# SubNav
subnav:
  github: "https://github.com/kangqf"
  weibo: "http://weibo.com/kangqingfei"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  google: "https://plus.google.com/115553302156535564722"
  #twitter: "#"
  #linkedin: "#"  
  rss: "/atom.xml"

#rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'xxxxxx'

favicon: /favicon.ico

#你的头像url
avatar: /assest/images/kqf.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
duoshuo: kangqingfei
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  奥巴马的博客: http://www.baidu.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 冷小飞侠去哪了,来个友链吧
